https://github.com/XcrigX/keycloak-extensions-for-fhir/blob/main/Dockerfile

version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2-legacy
    container_name: keycloak-18.0.2-legacy-smart
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
      - KC_HOSNTAME_STRICT=false
      - KC_IMPORT_REALM=/opt/jboss/keycloak/data/import/realm.json
    ports: 
      - "8082:8080"
    expose:
      - 8080
    command: 
      - --start-mode=normal 
    volumes:
       - ./config/realm.json:/opt/jboss/keycloak/data/import/realm.json
