version: '3.7'
services:
  keycloak:
    container_name: keycloak-smart-fhir
    image: kc-smart-fhir-poc
    build:
      context: "https://github.com/Alvearie/keycloak-extensions-for-fhir.git#main"
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "8080:8080"
      - "8443:8443"
    command:
      - --start-mode=normal
    volumes:
      - ./kc_config/realm.json:/tmp/realm.json
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      - "KEYCLOAK_IMPORT=/tmp/realm.json"
