version: '3.8'
services:
  keycloak:
    container_name: keycloak-alvearie-smart
    image: alvearie_keycloak
    build:
      context: https://github.com/Alvearie/keycloak-extensions-for-fhir.git#main
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
      - "8448:8443"
    command:
      - --start-mode=normal
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
  keycloak-config:
    container_name: keycloak-config-builder
    depends_on:
      - keycloak
    build:
      context: https://github.com/Alvearie/keycloak-extensions-for-fhir.git#main
      dockerfile: keycloak-config/Dockerfile
    command:
      - -configFile /tmp/conf/keycloak-config.json
    environment:
      - KEYCLOAK_BASE_URL=http://host.docker.internal:8080/auth
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_REALM=test
      - FHIR_BASE_URL=https://localhost:9443/fhir-server/api/r4
    volumes:
      - ./config:/tmp/config