version: '3.7'
services:
  keycloak:
    container_name: keycloak-alvearie-smart
    image: alvearie-smart-keycloak
    build:
      context: "https://github.com/Alvearie/keycloak-extensions-for-fhir.git#main"
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
      - "8443:8443"
    command:
      - --start-mode=normal
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
  keycloak-config:
    depends_on:
      - keycloak
    build:
      context: https://github.com/Alvearie/keycloak-extensions-for-fhir.git#main"
      dockerfile: keycloak-config/Dockerfile
    environment:
      - KEYCLOAK_BASE_URL=http://host.docker.internal:8080/auth
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_REALM=test
      - FHIR_BASE_URL=https://localhost:9443/fhir-server/api/v4=value