version: '3.7'
services:
  keycloak:
    container_name: idp-keycloak
    image: idp-keycloak
    build:
      context: "https://github.com/Alvearie/keycloak-extensions-for-fhir.git#main"
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "8088:8080"
      - "8448:8443"
    command:
      - --start-mode=normal
    volumes:
      - ./realm.json:/tmp/realm.json
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      - "KEYCLOAK_IMPORT=/tmp/realm.json"
