services:
  smart-launcher:
    container_name: smart-launcher
    image: smart-launcher
    build:
      context: https://github.com/smart-on-fhir/smart-launcher.git#master
      dockerfile: Dockerfile
    ports:
      - "9009:80"
    environment:
      - FHIR_SERVER_R2=https://lra-dev.bchealthcloud.ca/fhir
      - FHIR_SERVER_R3=https://lra-dev.bchealthcloud.ca/fhir
      - FHIR_SERVER_R4=https://lra-dev.bchealthcloud.ca/fhir
      - PICKER_CONFIG_R4=r4
      - NODE_ENV=development