version: '3.8'
services:
  keycloak-config:
    container_name: keycloak-config-builder
    build:
      context: https://github.com/Alvearie/keycloak-extensions-for-fhir.git#main
      dockerfile: keycloak-config/Dockerfile
    command:
      - -configFile /tmp/keycloak-config.json
    environment:
      - KEYCLOAK_BASE_URL=http://host.docker.internal:8080/auth
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_REALM=test
      - FHIR_BASE_URL=https://localhost:9443/fhir-server/api/r4
    volumes:
      - ./keycloak-config.json:/tmp/keycloak-config.json