version: '3.7'
services:
  keycloak:
    container_name: keycloak-smart-fhir
    image: kc-smart-fhir-poc
    build:
      context: "https://github.com/Alvearie/keycloak-extensions-for-fhir.git#main"
      dockerfile: Dockerfile
    ports: 
      - "8081:8080"
    command:
      - --start-mode=normal
    volumes:
      - ./config/keycloak-config.json:/opt/keycloak/conf/keycloak.json
      - ./config/realm-smart.json:/tmp/realm.json
    environment:
      - "KEYCLOAK_PASSWORD=admin"
      - "KEYCLOAK_IMPORT=/tmp/realm.json"
