version: '3.8'
services:
  keycloak:
    container_name: keycloak-alvearie-smart-on-fhir
    image: keycloak-alvearie-extended-1802
    build:
      context: https://github.com/bradhead/keycloak-extensions-for-fhir.git#main
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    command:
      - --start-mode=normal
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      - "KEYCLOAK_IMPORT=/tmp/import/lra-realm.json"
    volumes:
      - ./realm/:/tmp/import/